const COPY = [
 ['Search the web with AI','Cari web dengan AI','使用 AI 搜索网页'],
 ['Searches online sources for your plant symptom.','Mencari sumber dalam talian untuk gejala tanaman anda.','搜索与你的植物症状相关的在线资料。'],
 ['Searching the web…','Sedang mencari web…','正在搜索网页…'],
 ['From the web','Daripada web','网页资料'],['AI search','Carian AI','AI 搜索'],
 ['AI web research, not a confirmed plant diagnosis.','Penyelidikan web AI, bukan diagnosis tanaman yang disahkan.','AI 网页研究，并非植物确诊。'],
 ['You’re offline. Web search needs an internet connection.','Anda di luar talian. Carian web memerlukan internet.','你处于离线状态，网页搜索需要联网。'],
 ['AI web search is not available yet. Local guides are still available.','Carian web AI belum tersedia. Panduan tempatan masih tersedia.','AI 网页搜索尚未启用，本地指南仍可使用。'],
 ['Web search is busy. Try again in a minute.','Carian web sibuk. Cuba lagi dalam seminit.','网页搜索繁忙，请稍后重试。'],
 ['Web search took too long. Please try again.','Carian web mengambil masa terlalu lama. Sila cuba lagi.','网页搜索超时，请重试。'],
 ['Web search is unavailable right now. Please try again later.','Carian web tidak tersedia sekarang. Sila cuba lagi kemudian.','网页搜索暂不可用，请稍后重试。'],
 ['What’s visible','Apa yang kelihatan','可见特征'],
 ['Plant help tools','Alat bantuan tanaman','植物帮助工具'],['Camera','Kamera','相机'],['Search','Cari','搜索'],['Matching guides','Panduan sepadan','匹配指南'],['Common problems','Masalah biasa','常见问题'],['{count} guide','{count} panduan','{count} 篇指南'],['{count} guides','{count} panduan','{count} 篇指南'],
 ['No matching guides yet','Tiada panduan sepadan','暂无匹配指南'],['Try a symptom such as yellow leaves, holes or wilting.','Cuba gejala seperti daun kuning, lubang atau layu.','试试黄叶、孔洞或萎蔫等症状。'],['Show all guides','Lihat semua panduan','查看全部指南'],['What’s happening?','Apa yang berlaku?','植物怎么了？'],['Search plant problems','Cari masalah tanaman','搜索植物问题'],['Pests, yellow leaves, wilting…','Perosak, daun kuning, layu…','害虫、黄叶、萎蔫…'],['Search guides','Cari panduan','搜索指南'],['Filter guides','Tapis panduan','筛选指南'],['All problems','Semua masalah','全部问题'],['Pests','Perosak','害虫'],['Disease','Penyakit','病害'],['Growing conditions','Keadaan pertumbuhan','生长条件'],['Browse all learning','Lihat bahan pembelajaran','浏览学习内容'],
 ['Guide not found','Panduan tidak ditemui','未找到指南'],['Try another guide','Cuba panduan lain','试试其他指南'],['Search the symptom you can see.','Cari gejala yang kelihatan.','搜索你观察到的症状。'],['Search problems','Cari masalah','搜索问题'],['Plant problems','Masalah tanaman','植物问题'],['Look for','Perhatikan','观察要点'],['What to do first','Langkah awal','先做什么'],['When to get help','Bila perlu bantuan','何时寻求帮助'],['Sources & further reading','Sumber & bacaan lanjut','来源与延伸阅读'],['Check a plant photo','Semak foto tanaman','查看植物照片'],['Check your plant','Periksa tanaman anda','检查你的植物'],
 ['Photo summary','Ringkasan foto','照片摘要'],['Next steps','Langkah seterusnya','下一步'],['AI-generated observations, not a confirmed diagnosis.','Pemerhatian dijana AI, bukan diagnosis yang disahkan.','AI 生成的观察结果，并非确诊。'],['Guides to compare','Panduan untuk dibandingkan','参考指南'],['No close guide match. Search the symptoms you can see.','Tiada panduan yang hampir sepadan. Cari gejala yang kelihatan.','没有相近指南，请搜索你看到的症状。'],['Try a clear photo of a plant, leaf or pest.','Cuba foto tanaman, daun atau perosak yang jelas.','试着拍一张清晰的植物、叶片或害虫照片。'],['Search all problems','Cari semua masalah','搜索所有问题'],
 ['Photos to compare','Foto untuk dibandingkan','对比照片'],['Examples, not a diagnosis of your photo.','Contoh sahaja, bukan diagnosis foto anda.','仅供对比，并非照片诊断。'],['Read article','Baca artikel','阅读文章'],['Research sources','Sumber kajian','研究来源'],
 ['Your selected plant photo','Foto tanaman pilihan anda','你选择的植物照片'],['A leaf, a stem, a clue.','Daun, batang, petunjuk.','一片叶，一段茎，一条线索。'],['Preparing your photo…','Menyediakan foto…','正在处理照片…'],['Looking at your plant…','Memeriksa tanaman…','正在查看植物…'],['Take a plant photo','Ambil foto tanaman','拍摄植物照片'],['Choose a plant photo','Pilih foto tanaman','选择植物照片'],['Cancel','Batal','取消'],['Analyze again','Analisis semula','重新分析'],['Analyze photo','Analisis foto','分析照片'],['Retake','Ambil semula','重拍'],['Take a photo','Ambil foto','拍照'],['Choose a photo','Pilih foto','选择照片'],['Only Analyze sends your photo to OpenAI. It isn’t saved in this app.','Hanya Analisis menghantar foto ke OpenAI. Foto tidak disimpan dalam aplikasi ini.','只有点击分析才会将照片发送至 OpenAI，本应用不会保存照片。'],['Search problems instead','Cari masalah dahulu','改为搜索问题'],
 ['Choose a JPEG, PNG, WebP or supported phone photo.','Pilih foto JPEG, PNG, WebP atau format telefon yang disokong.','请选择 JPEG、PNG、WebP 或支持的手机照片。'],['Choose a photo smaller than 15 MB.','Pilih foto kurang daripada 15 MB.','请选择小于 15 MB 的照片。'],['This photo is too large to prepare. Choose a smaller image.','Foto terlalu besar. Pilih imej yang lebih kecil.','照片过大，请选择较小的图片。'],['This browser could not prepare the photo.','Pelayar ini tidak dapat menyediakan foto.','浏览器无法处理照片。'],['Choose a smaller photo and try again.','Pilih foto yang lebih kecil dan cuba lagi.','请选择较小的照片后重试。'],['This photo format could not be opened. Try a JPEG or PNG.','Format foto tidak dapat dibuka. Cuba JPEG atau PNG.','无法打开此格式，请尝试 JPEG 或 PNG。'],['The photo summary was incomplete. Please try again.','Ringkasan foto tidak lengkap. Sila cuba lagi.','照片摘要不完整，请重试。'],['Photo analysis returned an unreadable response. Please try again.','Respons analisis tidak dapat dibaca. Sila cuba lagi.','无法读取分析结果，请重试。'],['Photo analysis is unavailable. Try again or search the guides.','Analisis foto tidak tersedia. Cuba lagi atau cari panduan.','照片分析暂不可用，请重试或搜索指南。'],['The photo could not be opened.','Foto tidak dapat dibuka.','无法打开照片。'],['That took too long. Try again or search the guides.','Masa menunggu terlalu lama. Cuba lagi atau cari panduan.','等待超时，请重试或搜索指南。'],['Could not connect. Check your connection or search the guides.','Tidak dapat bersambung. Semak sambungan atau cari panduan.','无法连接，请检查网络或搜索指南。'],['Photo analysis is unavailable.','Analisis foto tidak tersedia.','照片分析暂不可用。'],['Photo analysis is not available yet. You can search the guides instead.','Analisis foto belum tersedia. Anda boleh mencari panduan dahulu.','照片分析尚未启用，你可以先搜索指南。'],['Please wait a minute before requesting another photo summary.','Sila tunggu seminit sebelum meminta ringkasan foto lain.','请稍等一分钟后再请求照片摘要。'],
 ['Skip to content','Langkau ke kandungan','跳至内容'],['Made for life in the field.','Dibina untuk kehidupan di ladang.','为田间生活而造。'],['Close','Tutup','关闭'],['Your farm, one tap away.','Ladang anda, satu sentuhan sahaja.','轻点即可进入农场。'],['On Android, open Aura in Chrome, tap the three-dot menu, then tap Install app or Add to Home screen. If you opened Aura inside another app, choose Open in Chrome first.','Di Android, buka Aura dalam Chrome, ketik menu tiga titik, kemudian ketik Pasang aplikasi atau Tambah ke skrin utama. Jika Aura dibuka dalam aplikasi lain, pilih Buka dalam Chrome dahulu.','在 Android 上用 Chrome 打开 Aura，点按三点菜单，然后选择“安装应用”或“添加到主屏幕”。如果 Aura 是在其他应用内打开的，请先选择“在 Chrome 中打开”。'],['On iPhone, open Aura in Safari, tap Share, then Add to Home Screen.','Di iPhone, buka Aura dalam Safari, ketik Kongsi, kemudian Tambah ke Skrin Utama.','在 iPhone 上用 Safari 打开 Aura，轻点分享，再选择添加到主屏幕。'],['Open your browser menu and choose Install app or Add to Home screen.','Buka menu pelayar dan pilih Pasang aplikasi atau Tambah ke skrin utama.','打开浏览器菜单，选择“安装应用”或“添加到主屏幕”。'],['Got it','Faham','知道了'],['A new version is ready.','Versi baharu tersedia.','新版本已就绪。'],['Refresh app','Muat semula aplikasi','刷新应用'],['Aura is already installed.','Aura telah dipasang.','Aura 已安装。'],['Installation requested.','Pemasangan diminta.','已请求安装。'],['Installation could not start. Try your browser menu.','Pemasangan tidak dapat dimulakan. Cuba menu pelayar.','无法开始安装，请尝试浏览器菜单。'],['Offline setup did not finish. Reopen the app when connected.','Persediaan luar talian belum selesai. Buka semula aplikasi apabila bersambung.','离线设置未完成，请联网后重新打开应用。'],
];
export const PLANT_TRANSLATIONS = { ms: Object.fromEntries(COPY.map(([key, ms]) => [key, ms])), 'zh-Hans': Object.fromEntries(COPY.map(([key, , zh]) => [key, zh])) };

// Guide IDs and source references stay canonical; only reading content is localized.
export const PLANT_GUIDE_COPY = {
 ms: {
  aphids: {title:'Kutu daun pada pucuk muda',summary:'Serangga lembut berkumpulan, pucuk melengkung dan daun melekit mungkin menandakan kutu daun. Periksa pucuk sebelum bertindak.',symptoms:['Periksa bawah daun muda dan batang lembut untuk serangga kecil berbentuk pir, berwarna hijau hingga hitam.','Daun mungkin melengkung atau kuning, dengan embun madu, semut atau kulapuk gelap. Tanda ini sahaja tidak mengesahkan kutu daun.'],actions:['Periksa beberapa pokok terjejas dan pokok sihat berdekatan. Ambil foto dekat serangga dan perhatikan pertumbuhan pucuk.','Pada pokok tegap dalam kawasan kecil, gunakan air untuk menanggalkan kutu pada awal hari supaya daun sempat kering. Elakkan semburan kuat pada anak benih.','Pelihara kumbang kura-kura dan musuh semula jadi lain. Elakkan semburan berspektrum luas atau nitrogen tambahan tanpa keperluan.'],whenToGetHelp:'Dapatkan nasihat jika koloni membesar, anak benih lemah atau daun baharu kekal cacat. Foto tidak dapat mengesahkan virus yang mungkin dibawa kutu daun.',keywords:['kutu daun','daun melekit','semut','pucuk melengkung']},
  whiteflies: {title:'Lalat putih di bawah daun',summary:'Serangga putih kecil yang terbang apabila daun bergerak mungkin lalat putih. Peringkat muda melekat di bawah daun.',symptoms:['Terbalikkan daun perlahan-lahan. Cari serangga dewasa putih bersayap dan serangga muda pucat yang leper di bawah daun.','Daun mungkin melekit, kuning atau cacat dengan kulapuk jelaga. Perosak penghisap sap lain boleh menyebabkan tanda serupa.'],actions:['Periksa daun muda dan tua pada beberapa pokok, termasuk anak benih baharu. Catat kawasan terjejas sebelum memindahkan pokok.','Kad pelekat kuning membantu memantau serangga dewasa, tetapi periksa daun juga. Bilangan dalam perangkap tidak mewakili seluruh populasi.','Lindungi pemangsa dan tebuan parasitoid. Elakkan racun berspektrum luas tanpa keperluan; buang daun teruk hanya jika pokok mampu menanggungnya.'],whenToGetHelp:'Dapatkan nasihat jika anak benih merosot, populasi meningkat atau perubahan bentuk dan warna daun berterusan; ujian virus mungkin diperlukan.',keywords:['lalat putih','serangga putih','daun melekit']},
  leafminers: {title:'Jejak berliku dalam daun',summary:'Terowong pucat dalam daun mungkin akibat pelombong daun. Larva hidup di antara permukaan daun.',symptoms:['Cari jejak putih berliku yang semakin lebar dan tusukan kecil tempat lalat makan atau bertelur.','Periksa anak pokok dan sayur berdaun dengan teliti. Tanda lama boleh kekal selepas serangga keluar.'],actions:['Bandingkan daun baharu dan lama untuk terowong baharu. Halakan daun ke cahaya tanpa mengoyakkannya.','Periksa anak benih sebelum dipindahkan. Jika ada lokasi sesuai, jauhkan daripada tanaman yang teruk diserang dan hampir dituai.','Bersihkan sisa tanaman terjejas selepas tuaian dan urus rumpai perumah. Pelihara tebuan parasitoid dengan mengelakkan semburan berspektrum luas tanpa keperluan.'],whenToGetHelp:'Minta pemeriksaan jika kerosakan merebak pada anak benih atau daun untuk jualan. Tindakan bergantung pada tanaman, peringkat pertumbuhan dan serangan aktif.',keywords:['pelombong daun','jejak putih','terowong daun']},
  caterpillars: {title:'Lubang daun dan ulat',summary:'Lubang baharu pada kubis atau sawi mungkin disebabkan ulat. Periksa bawah daun dan titik pertumbuhan.',symptoms:['Larva muda rama-rama belakang intan meninggalkan tompok nipis lut sinar; larva lebih tua membuat lubang. Siput dan ulat lain juga boleh menyebabkan kerosakan serupa.','Cari larva hijau kecil di bawah daun dan sekitar tunas. Larva belakang intan sering menggeliat atau jatuh dengan benang sutera apabila diganggu.'],actions:['Periksa beberapa pokok termasuk barisan tepi. Ambil foto larva bersama kerosakan dan kira pokok terjejas.','Periksa anak benih dan kepala kubis yang sedang membentuk. Bezakan serangga aktif daripada lubang lama yang tidak bertambah.','Pelihara musuh semula jadi dan elakkan semburan rutin berspektrum luas. Rancang penggiliran tanaman bersama penasihat untuk musim seterusnya.'],whenToGetHelp:'Dapatkan pengenalpastian jika pucuk rosak, larva masuk ke kepala kubis atau kerosakan bertambah. Jenis ulat dan rintangan racun mempengaruhi pengurusan.',keywords:['ulat','lubang daun','daun dimakan','sawi','kubis']},
  'rice-planthoppers': {title:'Benah pada padi',summary:'Benah menghisap di bahagian bawah batang padi dan boleh mengeringkan kelompok pokok. Periksa pangkal rumpun.',symptoms:['Cari serangga kecil pucat hingga perang di bawah batang. Ketukan lembut pada pokok yang dibengkokkan boleh menjatuhkannya ke air.','Serangan berat boleh menukar padi jingga-kuning, kemudian perang dan kering. Cari serangga walaupun embun madu atau kulapuk kelihatan.'],actions:['Periksa pangkal pokok di beberapa tempat. Catat peringkat tanaman, kelompok terjejas, bilangan serangga dan musuh semula jadi seperti labah-labah.','Elakkan racun awal atau berspektrum luas tanpa keperluan. Semak penggunaan nitrogen bersama penasihat, jangan terus menambah baja pada tompok kuning.','Terus pantau perubahan. Untuk musim seterusnya, tanya tentang varieti tahan yang sesuai dan cara mengelakkan kanopi terlalu padat.'],whenToGetHelp:'Hubungi penasihat padi segera jika tompok kering meluas atau populasi meningkat. Foto daun sahaja tidak dapat membezakan kerosakan benah daripada punca lain.',keywords:['benah perang','padi kuning','tompok kering','padi']},
  'rice-blast': {title:'Tompok yang mungkin karah padi',summary:'Karah boleh menghasilkan lesi daun runcing dengan pusat pucat. Tompok serupa mempunyai punca lain; kumpulkan bukti untuk pengenalpastian.',symptoms:['Lesi lama sering berbentuk gelendong, hujung runcing, pusat kelabu atau putih dan tepi perang. Lesi boleh bercantum.','Periksa sambungan helaian daun dan pelepah. Tompok perang lebih bulat dengan tepi kuning mungkin masalah lain.'],actions:['Ambil foto seluruh pokok, beberapa lesi dan kawasan terjejas dalam cahaya siang. Catat varieti, peringkat tanaman, hujan dan bila gejala bermula.','Jangan tambah nitrogen kerana daun rosak. Bincangkan program nitrogen berperingkat yang seimbang dan pengurusan air dengan penasihat.','Pantau pokok sekeliling dan penyebaran tompok. Tanya tentang varieti tahan karah yang sesuai untuk tanaman seterusnya.'],whenToGetHelp:'Aturkan pemeriksaan segera jika lesi merebak atau padi hampir keluar tangkai. Karah boleh menyerang bahagian selain daun; foto tidak mencukupi untuk memilih rawatan.',keywords:['karah','penyakit padi','tompok perang','bintik daun']},
  'yellow-leaves': {title:'Mengapa daun menjadi kuning',summary:'Daun kuning ialah gejala, bukan diagnosis. Air, nutrien, serangga, penyakit atau penuaan boleh menjadi punca.',symptoms:['Catat sama ada daun tua bawah atau pucuk baharu mula kuning, dan sama ada seluruh daun berubah atau urat kekal hijau.','Beberapa daun tua kuning berbeza daripada banyak pokok yang cepat kuning. Cari juga layu, tompok, serangga dan akar rosak.'],actions:['Periksa kelembapan tanah di bawah permukaan dan perosak di bawah daun. Bandingkan dengan pokok sihat yang sama tanaman dan umur.','Catat pengairan, hujan lebat, baja dan semburan terkini. Ambil foto seluruh pokok serta daun supaya corak kerosakan jelas.','Jangan tambah baja semata-mata kerana daun kuning. Jika disyaki kekurangan nutrien, minta ujian nutrien dan pH tanah.'],whenToGetHelp:'Dapatkan nasihat jika kekuningan merebak, pucuk baharu terjejas atau pokok layu walaupun lembapan sesuai. Ujian mungkin diperlukan.',keywords:['daun kuning','kekurangan nutrien','daun pucat']},
  'water-stress': {title:'Layu akibat haba atau tanah kering',summary:'Daun terkulai boleh menandakan tekanan air, tetapi cuaca panas, akar basah dan penyakit boleh kelihatan serupa. Periksa tanah dahulu.',symptoms:['Daun mungkin terkulai ketika paling panas dan pulih apabila sejuk. Layu berterusan, tepi kering dan pertumbuhan perlahan perlu diperiksa.','Rasa tanah di bawah permukaan dekat akar, di beberapa tempat. Kerak kering di atas sahaja tidak menunjukkan bekalan air akar.'],actions:['Periksa semula pada pagi yang sejuk. Catat pemulihan, hujan, pengairan, haba dan angin terkini.','Jika kawasan akar kering, siram perlahan pada aras tanah dan nilai semula. Sesuaikan kekerapan dengan tanaman, tanah dan cuaca.','Periksa saluran pengairan tersumbat dan siraman tidak sekata. Jika tanah tepu air, periksa saliran; air tambahan boleh memburukkan keadaan.'],whenToGetHelp:'Minta diagnosis jika layu berterusan selepas lembapan dibetulkan, sebelah pokok rebah atau batang dan akar reput.',keywords:['layu','kemarau','tanah kering','tekanan haba','kurang air']},
  waterlogging: {title:'Tanah basah dan akar tertekan',summary:'Sayur boleh layu walaupun tanah basah. Saliran lemah mengurangkan udara pada akar. Panduan ini untuk batas sayur dan bekas, bukan padi sawah.',symptoms:['Cari layu atau kekuningan selepas hujan lama, pengairan atau air bertakung. Bandingkan tempat rendah dengan kawasan bersaliran baik.','Periksa lubang saliran dan tanah bawah permukaan. Akar lembut perang atau pangkal reput memerlukan siasatan lanjut.'],actions:['Hentikan pengairan yang tidak perlu semasa tanah tepu. Bersihkan lubang saliran yang mudah dicapai tanpa merosakkan akar.','Elakkan berjalan, menggali atau menggunakan mesin di batas tepu air. Catat tempat dan tempoh air bertakung selepas hujan.','Baiki saliran dan pertimbangkan batas tinggi untuk tanaman akan datang. Jangan kerap mengganggu akar anak benih semasa pemeriksaan.'],whenToGetHelp:'Dapatkan nasihat jika pokok masih rebah selepas saliran baik atau akar dan batang reput; puncanya mungkin berbeza.',keywords:['air bertakung','tanah basah','akar reput','terlebih siram','saliran']},
  snails: {title:'Siput dan anak benih hilang',summary:'Anak padi hilang atau daun sayur koyak mungkin akibat siput. Kenal pasti haiwan dan tanaman sebelum bertindak.',symptoms:['Siput gondang boleh memotong batang anak padi dekat pangkal. Kelompok telur merah jambu terang di atas air ialah petunjuk.','Pada sayur, cari lubang tidak sekata, anak benih rosak dan jejak lendir keperakan. Siput tanpa cangkerang boleh bersembunyi dalam sisa lembap.'],actions:['Periksa tempat lembap awal pagi atau malam. Gunakan sarung tangan atau alat untuk mengutip. Ambil foto haiwan, telur dan kerosakan.','Untuk padi, periksa saluran masuk air. Bincangkan penapis dan pengurusan air mengikut peringkat tanaman; jangan pindahkan siput ke saluran lain.','Buang tempat persembunyian lembap yang tidak perlu di batas sayur. Jika sesuai, selaraskan kutipan siput dan telur padi dengan jiran.'],whenToGetHelp:'Dapatkan bantuan segera jika anak padi atau anak benih terus hilang. Pengurusan bergantung pada spesies, peringkat tanaman dan sistem air.',keywords:['siput','siput gondang','anak benih hilang','telur merah jambu']},
 },
 'zh-Hans': {
  aphids:{title:'嫩芽上的蚜虫',summary:'成群的软体小虫、卷曲的新梢和黏叶可能与蚜虫有关，先检查生长点。',symptoms:['检查嫩叶背面和嫩茎是否有梨形小虫，颜色可从绿色到黑色。','叶片可能卷曲或发黄，并出现蜜露、蚂蚁或黑霉；这些现象本身不能确诊蚜虫。'],actions:['检查多株受害植物及附近健康植物，近距离拍摄虫体，并观察新梢是否正常生长。','对小片区域的强健植物，可在清晨用水冲落蚜虫，让叶片有时间干燥；避免强水流伤害幼苗。','保护瓢虫、草蛉等天敌，避免不必要的广谱喷药或额外施氮催长。'],whenToGetHelp:'若虫群扩大、幼苗衰弱或新叶持续畸形，请咨询当地农技人员；照片无法确认蚜虫可能传播的病毒。',keywords:['蚜虫','黏叶','蚂蚁','卷叶']},
  whiteflies:{title:'叶片背面的粉虱',summary:'晃动叶片时飞起的小白虫可能是粉虱，若虫通常附着在叶背。',symptoms:['轻轻翻转叶片，寻找白色有翅成虫及附着在叶背的浅色扁平若虫。','叶片可能黏腻、发黄或畸形，蜜露上可长煤污霉；其他刺吸式害虫也可能引起相似症状。'],actions:['检查多株植物的新老叶，包括新买的幼苗；搬动植物前记录受害范围。','黄板有助于监测成虫，但仍须检查叶片；诱捕数量不能代表全部虫口或证明黄叶原因。','保护捕食性天敌及寄生蜂，避免不必要的广谱杀虫剂；仅在植物能承受时摘除严重受害叶片。'],whenToGetHelp:'幼苗衰退、虫量上升或叶片持续畸形、异常变色时，请咨询当地人员，可能需要病毒检测。',keywords:['粉虱','白虫','黏叶','煤污病']},
  leafminers:{title:'叶片内弯曲的虫道',summary:'叶片内部的浅色隧道可能由潜叶虫造成，幼虫在叶片表层之间取食。',symptoms:['寻找逐渐变宽的白色弯曲虫道，以及成虫取食或产卵留下的小针点。','特别留意幼苗和食用叶菜；虫子离开后，旧叶上的伤痕仍可能保留。'],actions:['比较新老叶，记录是否出现新虫道；将叶片对着光观察，不必撕开。','移栽前检查育苗材料；如有合适位置，避免将幼苗放在临近收获且严重受害的作物旁。','收获后清理受害残体并管理寄主杂草，避免不必要的广谱喷药以保护寄生蜂。'],whenToGetHelp:'若幼苗或准备出售的叶片损伤扩大，请农技人员检查；后续处理取决于作物、生长期及当前虫情。',keywords:['潜叶虫','潜叶蝇','白色虫道','弯曲线条']},
  caterpillars:{title:'叶片孔洞与毛虫',summary:'甘蓝或芥菜的新鲜孔洞可能来自毛虫，检查叶背和生长点寻找虫体。',symptoms:['小菜蛾幼虫可留下半透明薄斑，较大幼虫会咬出孔洞；其他毛虫或蜗牛也可造成类似损伤。','检查叶背和芽周的小绿虫；小菜蛾幼虫受惊时常扭动或吐丝下坠。'],actions:['检查多株植物及田边行，拍摄虫体与受害部位，并记录受害株数。','定期检查幼苗和正在结球的植株；区分活跃虫害与不再增加的旧孔洞。','保护天敌，避免常规广谱喷药；为下一季规划轮作，并与农技人员讨论邻近十字花科作物的种植安排。'],whenToGetHelp:'若生长点受损、幼虫钻入菜球或取食加重，应请人鉴定；不同毛虫及抗药性影响防治方法。',keywords:['毛虫','菜青虫','小菜蛾','孔洞','虫咬','叶子有洞']},
  'rice-planthoppers':{title:'水稻上的稻飞虱',summary:'稻飞虱在茎基部取食，可造成成片干枯；应检查分蘖基部。',symptoms:['寻找茎下部浅色至褐色的小虫；轻拍弯下的植株，可见虫体落到水面。','严重受害可由橙黄变为褐色干枯；基部可能有蜜露或黑霉，但仍需寻找虫体。'],actions:['在田间多个位置检查植株基部，记录生育期、受害区域、虫量及蜘蛛等天敌。','避免不必要的早期或广谱杀虫剂，防止杀伤天敌；与农技人员核查氮肥用量，不要直接给黄斑加肥。','持续调查并比较变化；为下一季咨询适宜的抗性品种及避免冠层过密的方法。'],whenToGetHelp:'干枯斑块扩大或虫量上升时，请及时联系水稻技术人员；单张叶片照片无法区分虱烧与其他衰退原因。',keywords:['稻飞虱','褐飞虱','虱烧','水稻发黄','水稻']},
  'rice-blast':{title:'可能与稻瘟病有关的斑点',summary:'稻瘟病可形成两端尖、中央浅色的病斑，但相似斑点也有其他原因，请收集鉴定依据。',symptoms:['较老病斑常呈梭形，尖端、灰白中心及褐色边缘；病斑可能连接。','同时检查叶片与叶鞘交界处；较圆的褐斑伴黄色边缘可能是其他问题。'],actions:['在日光下拍摄整株、多个病斑及受害区域，记录品种、生育期、近期降雨及初现时间。','不要因叶片受损而额外施氮；与当地技术人员讨论均衡分次施氮及适宜水分管理。','监测周围植株及斑点扩展；咨询适合当地生产条件的抗稻瘟病品种。'],whenToGetHelp:'病斑扩散或临近抽穗时应尽快检查；稻瘟病不只影响叶片，照片不足以决定治疗。',keywords:['稻瘟病','水稻病害','褐斑','叶斑','灰色斑点']},
  'yellow-leaves':{title:'叶片为什么变黄',summary:'黄叶是症状，不是诊断；水分、营养、害虫、病害及自然衰老都可能导致变色。',symptoms:['记录从下部老叶还是新叶开始，以及整片变黄还是叶脉仍绿。','少数老叶变黄与大量植株迅速变黄不同；同时检查萎蔫、斑点、虫体和根部损伤。'],actions:['检查表层以下的土壤湿度及叶背害虫，与同作物、同龄健康植株比较。','记录近期灌溉、暴雨、施肥及喷药；拍摄整株和单叶，保留症状分布信息。','不要仅因黄叶而施肥；怀疑营养问题时咨询土壤养分及酸碱度检测，按确认的需求调整投入。'],whenToGetHelp:'黄叶扩散、新生长受影响或湿度合适仍萎蔫时，请寻求当地建议；可能需要检测区分根病与营养问题。',keywords:['黄叶','叶子发黄','缺素','缺氮','叶片变黄']},
  'water-stress':{title:'高温或干土中的萎蔫',summary:'蔬菜叶片下垂可能与缺水有关，但高温、湿根和病害也很相似，补水前先查土壤。',symptoms:['叶片可在最热时下垂、凉快后恢复；持续萎蔫、干边及生长缓慢需要进一步检查。','在根区附近多个位置检查表层以下土壤；干燥表皮不能代表根部缺水。'],actions:['在凉爽清晨复查恢复情况，记录近期降雨、灌溉、异常高温和大风。','根区确实干燥时，在地面缓慢浇水，让水到达根部后再评估；频率应依作物、土壤和天气调整。','检查堵塞的灌溉出口及浇水不均；土壤已饱和时，应调查排水问题，继续加水可能加重根部压力。'],whenToGetHelp:'纠正水分后仍萎蔫、单侧倒伏或根茎腐烂时，请寻求当地诊断，灌溉可能无法解决。',keywords:['萎蔫','枯萎','缺水','干旱','高温','干土']},
  waterlogging:{title:'湿土与受压的根系',summary:'蔬菜在湿土中也会萎蔫，排水差会减少根部空气并促进病害。本指南适用于菜畦和容器，不适用于水田。',symptoms:['观察长期降雨、灌溉或积水后的萎蔫、黄叶，并比较低洼处与排水较好区域。','检查排水孔及表层以下土壤；褐色软根或腐烂茎基部需进一步调查，外观无法确定具体根病。'],actions:['根区饱和时暂停不必要的灌溉，在不损伤根系的前提下清理可触及的排水孔和现有排水沟。','避免在积水菜畦上行走、挖掘或操作机械以免压实，记录积水位置和雨后持续时间。','为下一次种植改善排水，必要时考虑高畦；检查幼苗时保护根系，避免反复扰动。'],whenToGetHelp:'改善排水后仍倒伏，或根茎持续腐烂时，请咨询当地人员；根系损伤与土传病害可能需要不同处理。',keywords:['积水','涝害','湿土','烂根','浇水过多','排水']},
  snails:{title:'蜗牛与消失的幼苗',summary:'水稻幼苗缺株或蔬菜叶缘破损可能与蜗牛有关，请先辨认动物并结合具体作物判断。',symptoms:['福寿螺可咬断幼稻近基部的茎；水面上方物体上的鲜粉红卵块是线索。','蔬菜上可见不规则孔洞、嫩苗损伤和银色黏液痕；无壳蛞蝓白天可能躲在潮湿残物下。'],actions:['清晨或天黑后检查潮湿处，用手套或工具收集；拍摄动物、卵和损伤，不只拍受害叶片。','水田应检查进水口，与当地技术人员讨论拦网和按生育期管理水位，勿将螺转移至其他水道。','清理菜畦不必要的潮湿藏身处，检查木板及杂物下方；条件允许时与邻田协调收集螺和卵。'],whenToGetHelp:'幼稻或幼苗持续缺失时应及时求助；管理取决于螺种、生育期和田间水系统。',keywords:['蜗牛','福寿螺','蛞蝓','幼苗消失','粉红卵']},
 }
};
